import { StageDefinition } from './types'

export const STAGE_DEFINITIONS: StageDefinition[] = [
  {
    id: 'stage_1',
    nameKey: 'STAGE_NAME_STAGE_1',
    descriptionKey: 'STAGE_DESC_STAGE_1',
    mapRadius: 4,
    totalTurns: 40,
    waves: [
      {
        triggerTurn: 2,
        totalCost: 40,
        enemyPool: ['enemy_lv2'],
      },
      {
        triggerTurn: 8,
        totalCost: 60,
        enemyPool: ['enemy_lv2'],
      },
      {
        triggerTurn: 14,
        totalCost: 80,
        enemyPool: ['enemy_lv2', 'enemy_lv3'],
      },
      {
        triggerTurn: 20,
        totalCost: 100,
        enemyPool: ['enemy_lv2', 'enemy_lv3'],
      },
      {
        triggerTurn: 26,
        totalCost: 120,
        enemyPool: ['enemy_lv3'],
      },
      {
        triggerTurn: 32,
        totalCost: 70,
        enemyPool: ['enemy_lv2', 'enemy_lv3'],
      },
      {
        triggerTurn: 38,
        totalCost: 70,
        enemyPool: ['enemy_lv2', 'enemy_lv3'],
      },
    ],
    itemSpawns: [
      { itemType: 'dataChip', triggerTurn: 3, quantity: 1 },
      { itemType: 'spareBattery', triggerTurn: 5, quantity: 1 },
      { itemType: 'dataChip', triggerTurn: 10, quantity: 2 },
      { itemType: 'spareBattery', triggerTurn: 15, quantity: 1 },
      { itemType: 'dataChip', triggerTurn: 20, quantity: 1 },
      { itemType: 'spareBattery', triggerTurn: 25, quantity: 1 },
      { itemType: 'dataChip', triggerTurn: 30, quantity: 1 },
    ],
  },
  {
    id: 'stage_2',
    nameKey: 'STAGE_NAME_STAGE_2',
    descriptionKey: 'STAGE_DESC_STAGE_2',
    mapRadius: 5,
    totalTurns: 50,
    waves: [
      {
        triggerTurn: 2,
        totalCost: 40,
        enemyPool: ['enemy_lv2'],
      },
      {
        triggerTurn: 8,
        totalCost: 80,
        enemyPool: ['enemy_lv2', 'enemy_lv3'],
      },
      {
        triggerTurn: 14,
        totalCost: 120,
        enemyPool: ['enemy_lv2', 'enemy_lv3', 'enemy_lv4'],
      },
      {
        triggerTurn: 20,
        totalCost: 160,
        enemyPool: ['enemy_lv3', 'enemy_lv4'],
      },
      {
        triggerTurn: 26,
        totalCost: 200,
        enemyPool: ['enemy_lv3', 'enemy_lv4'],
      },
      {
        triggerTurn: 32,
        totalCost: 180,
        enemyPool: ['enemy_lv4', 'enemy_lv2'],
      },
      {
        triggerTurn: 36,
        totalCost: 220,
        enemyPool: ['enemy_lv4', 'enemy_lv3'],
      },
      {
        triggerTurn: 40,
        totalCost: 150,
        enemyPool: ['enemy_lv4'],
      },
      {
        triggerTurn: 46,
        totalCost: 220,
        enemyPool: ['enemy_lv4', 'enemy_lv3'],
      },
    ],
    itemSpawns: [
      { itemType: 'dataChip', triggerTurn: 5, quantity: 2 },
      { itemType: 'spareBattery', triggerTurn: 12, quantity: 1 },
      { itemType: 'dataChip', triggerTurn: 25, quantity: 3 },
      { itemType: 'spareBattery', triggerTurn: 40, quantity: 2 },
    ],
  },
  {
    id: 'stage_3',
    nameKey: 'STAGE_NAME_STAGE_3',
    descriptionKey: 'STAGE_DESC_STAGE_3',
    mapRadius: 6,
    totalTurns: 60,
    waves: [
      { triggerTurn: 2, totalCost: 60, enemyPool: ['enemy_lv2'] },
      { triggerTurn: 8, totalCost: 100, enemyPool: ['enemy_lv2', 'enemy_lv3'] },
      { triggerTurn: 14, totalCost: 150, enemyPool: ['enemy_lv2', 'enemy_lv3', 'enemy_lv4'] },
      { triggerTurn: 20, totalCost: 200, enemyPool: ['enemy_lv3', 'enemy_lv4'] },
      { triggerTurn: 26, totalCost: 250, enemyPool: ['enemy_lv3', 'enemy_lv4', 'enemy_lv5'] },
      { triggerTurn: 32, totalCost: 300, enemyPool: ['enemy_lv4', 'enemy_lv5'] },
      { triggerTurn: 36, totalCost: 350, enemyPool: ['enemy_lv4', 'enemy_lv5', 'enemy_lv6'] },
      { triggerTurn: 42, totalCost: 350, enemyPool: ['enemy_lv4', 'enemy_lv5', 'enemy_lv6'] },
      { triggerTurn: 48, totalCost: 400, enemyPool: ['enemy_lv5', 'enemy_lv6'] },
      { triggerTurn: 50, totalCost: 400, enemyPool: ['enemy_lv5', 'enemy_lv6'] },
      { triggerTurn: 52, totalCost: 300, enemyPool: ['enemy_lv5', 'enemy_lv6', 'enemy_lv7'] },
      { triggerTurn: 54, totalCost: 300, enemyPool: ['enemy_lv5', 'enemy_lv6', 'enemy_lv7'] },
      { triggerTurn: 56, totalCost: 300, enemyPool: ['enemy_lv5', 'enemy_lv6', 'enemy_lv7'] },
    ],
    itemSpawns: [
      { itemType: 'dataChip', triggerTurn: 7, quantity: 2 },
      { itemType: 'spareBattery', triggerTurn: 15, quantity: 1 },
      { itemType: 'dataChip', triggerTurn: 30, quantity: 3 },
      { itemType: 'spareBattery', triggerTurn: 50, quantity: 2 },
    ],
  },
  {
    id: 'stage_4',
    nameKey: 'STAGE_NAME_STAGE_4',
    descriptionKey: 'STAGE_DESC_STAGE_4',
    mapRadius: 7,
    totalTurns: 80,
    waves: [
      { triggerTurn: 2, totalCost: 80, enemyPool: ['enemy_lv2', 'enemy_lv3'] },
      { triggerTurn: 8, totalCost: 140, enemyPool: ['enemy_lv3', 'enemy_lv4'] },
      { triggerTurn: 14, totalCost: 200, enemyPool: ['enemy_lv3', 'enemy_lv4', 'enemy_lv5'] },
      { triggerTurn: 20, totalCost: 280, enemyPool: ['enemy_lv4', 'enemy_lv5'] },
      { triggerTurn: 26, totalCost: 350, enemyPool: ['enemy_lv4', 'enemy_lv5', 'enemy_lv6'] },
      { triggerTurn: 32, totalCost: 420, enemyPool: ['enemy_lv5', 'enemy_lv6'] },
      { triggerTurn: 38, totalCost: 390, enemyPool: ['enemy_lv5', 'enemy_lv6', 'enemy_lv7'] },
      { triggerTurn: 42, totalCost: 300, enemyPool: ['enemy_lv6', 'enemy_lv7'] },
      { triggerTurn: 48, totalCost: 300, enemyPool: ['enemy_lv6', 'enemy_lv7'] },
      { triggerTurn: 54, totalCost: 170, enemyPool: ['enemy_lv7'] },
      { triggerTurn: 60, totalCost: 170, enemyPool: ['enemy_lv7'] },
      { triggerTurn: 65, totalCost: 340, enemyPool: ['enemy_lv7'] },
      { triggerTurn: 70, totalCost: 340, enemyPool: ['enemy_lv7'] },
      { triggerTurn: 72, totalCost: 300, enemyPool: ['enemy_lv4'] },
      { triggerTurn: 74, totalCost: 200, enemyPool: ['enemy_lv3'] },
      { triggerTurn: 76, totalCost: 100, enemyPool: ['enemy_lv2'] },
      { triggerTurn: 78, totalCost: 340, enemyPool: ['enemy_lv7'] },
      { triggerTurn: 80, totalCost: 340, enemyPool: ['enemy_lv7'] },
    ],
    itemSpawns: [
      { itemType: 'dataChip', triggerTurn: 10, quantity: 3 },
      { itemType: 'spareBattery', triggerTurn: 20, quantity: 2 },
      { itemType: 'dataChip', triggerTurn: 30, quantity: 4 },
      { itemType: 'spareBattery', triggerTurn: 40, quantity: 2 },
      { itemType: 'dataChip', triggerTurn: 50, quantity: 3 },
      { itemType: 'spareBattery', triggerTurn: 60, quantity: 1 },
    ],
  },
]
